export const NET = {
  VBUS_5V: "net.VBUS_5V",
  V3_3: "net.V3_3",
  V1_1: "net.V1_1",
  GND: "net.GND",
  AGND: "net.AGND",

  USB_DP_CONN: "net.USB_DP_CONN",
  USB_DM_CONN: "net.USB_DM_CONN",
  USB_DP: "net.USB_DP",
  USB_DM: "net.USB_DM",

  VREG_LX: "net.VREG_LX",
  VREG_AVDD: "net.VREG_AVDD",

  XIN: "net.XIN",
  XOUT: "net.XOUT",
  XOUT_CRYSTAL: "net.XOUT_CRYSTAL",

  SWCLK: "net.SWCLK",
  SWDIO: "net.SWDIO",
  RUN: "net.RUN",
  USB_BOOT_N: "net.USB_BOOT_N",
  USB_BOOT_BTN: "net.USB_BOOT_BTN",

  UART0_TX: "net.UART0_TX",
  UART0_RX: "net.UART0_RX",
  I2C1_SDA: "net.I2C1_SDA",
  I2C1_SCL: "net.I2C1_SCL",
  SPI0_MISO: "net.SPI0_MISO",
  SPI0_CSN: "net.SPI0_CSN",
  SPI0_SCK: "net.SPI0_SCK",
  SPI0_MOSI: "net.SPI0_MOSI",

  ADC0: "net.ADC0",
  ADC1: "net.ADC1",
  ADC2: "net.ADC2",
  ADC3: "net.ADC3",

  GPIO8: "net.GPIO8",
  GPIO9: "net.GPIO9",
  GPIO10: "net.GPIO10",
  GPIO11: "net.GPIO11",
  GPIO12: "net.GPIO12",
  GPIO13: "net.GPIO13",
  GPIO14: "net.GPIO14",
  GPIO15: "net.GPIO15",
  GPIO16: "net.GPIO16",
  GPIO17: "net.GPIO17",
  GPIO18: "net.GPIO18",
  GPIO19: "net.GPIO19",
  GPIO20: "net.GPIO20",
  GPIO21: "net.GPIO21",
  GPIO22: "net.GPIO22",
  GPIO23: "net.GPIO23",

  USER_LED: "net.USER_LED",
  USER_LED_ANODE: "net.USER_LED_ANODE",
  PWR_LED_ANODE: "net.PWR_LED_ANODE",
} as const
